// Generated by CoffeeScript 1.4.0
(function() {
  var JipDom,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  JipDom = (function() {

    function JipDom(target, fillerImg, resize, height, width) {
      this.target = target;
      this.fillerImg = fillerImg;
      this.resize = resize;
      this.height = height;
      this.width = width;
      this.addModal = __bind(this.addModal, this);

      this.replaceInput = __bind(this.replaceInput, this);

      this.replaceInput();
    }

    JipDom.prototype.replaceInput = function() {
      var elem, refNode, replacement, selector;
      replacement = "<div class=\"jipSelector\">\n    <div class=\"jipPlaceHolder\">\n      " + this.fillerImg + "\n      <div class=\"jipImageName\">{image_name}</div>\n    </div>\n    <div><button class=\"jipSelectBtn\">select Image</button></div>\n</div>";
      selector = "jipPlaceHolder";
      document.getElementById(this.target).className += "hidden";
      refNode = document.getElementById(this.target);
      refNode.parentNode.insertBefore(replacement, refNode.nextSibling);
      if (this.resize) {
        elem = document.getElementById(selector);
        elem.setAttribute('height', this.height);
        elem.setAttribute('width', this.width);
      }
      return ture;
    };

    JipDom.prototype.addModal = function() {
      var modal;
      modal = "<div id=\"jipOverlay\">&nbsp;</div>\n    <div id=\"jipModal\">\n      <!-- start header -->\n      <div id=\"jipTitle\">\n        <h3>{{title}}</h3>\n        <form>\n          <label for=\"jipFolderSelect\">Change Folder</label>\n          <select id=\"jipFolderSelect\">\n            <option value='/url/main'>Main</option>\n            <option value='/url/avatar'>Avatar</option>\n          </select>\n        </form>\n        <div class=\"clearfix\">&nbsp;</div>\n      </div>\n      <!-- end Header -->\n\n      <!-- start modal body -->\n      <div id=\"jipBody\">\n        <ul>\n\n        </ul>\n      </div>\n      <!-- end modal body -->\n      <!-- start footer -->\n      <div id=\"jipFooter\">\n        <div class=\"clearfix\">&nbsp;</div>\n        <div id=\"jipPaging\">\n          <ul>\n            <li> <button id=\"jipPrev\"> Previous</button> </li>\n            <li> <button id=\"jipNext\"> Next</button> </li>\n          </ul>\n        </div>\n        <div id=\"jipAction\">\n          <ul>\n            <li> <button id=\"jipCancle\"> Cancel</button> </li>\n            <li> <button id=\"jipSave\"> Save</button> </li>\n          </ul>\n        </div>\n        <div class=\"clearfix\">&nbsp;</div>\n      </div>\n      <!-- end jip footer -->\n      </div>";
      return modal = "jipModal";
    };

    return JipDom;

  })();

}).call(this);
