// Generated by CoffeeScript 1.4.0
(function() {

  (function($, window, document) {
    var Plugin, defaults, pluginName;
    pluginName = "jip";
    defaults = {
      fillerImg: "http://placehold.it/200x200",
      getImagesFrom: null,
      galleryUrl: "/gallery/",
      modalTitle: "Select A Image",
      saveBtnText: "Save",
      paging: true,
      per_page: 10,
      showImageName: true,
      showFolders: true,
      folders: [
        {
          'main': '/url/main',
          'avatars': '/url/avatars'
        }
      ],
      allowDelete: true,
      resize: true,
      resizeHeight: 100,
      resizeWidth: 100
    };
    Plugin = (function() {

      function Plugin(element, options) {
        this.element = element;
        this.options = $.extend({}, defaults, options);
        this._defaults = defaults;
        this._name = pluginName;
        this.init();
      }

      Plugin.prototype.init = function() {};

      Plugin.prototype.yourOtherFunction = function() {};

      return Plugin;

    })();
    return $.fn[pluginName] = function(options) {
      return this.each(function() {
        if (!$.data(this, "plugin_" + pluginName)) {
          return $.data(this, "plugin_" + pluginName, new Plugin(this, options));
        }
      });
    };
  })(jQuery, window, document);

}).call(this);
